# Generated by Django 3.0.4 on 2020-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_auto_20200317_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_preview',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
